apiVersion: v1
kind: Template
metadata:
  name: aws-provision-security-group
parameters:
- name: vpc_name
  required: true
  value: openshift-vpc
- name: cluster_name
  required: true
  value: openshift-cluster

objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: aws-security-group-config
  data:
    security-groups.yaml: |
      security_groups:
      - name: ${cluster_name}-control-plane
        description: Security group for control plane nodes
        vpc_name: ${vpc_name}
        rules:
        - protocol: tcp
          from_port: 6443
          to_port: 6443
          cidr_blocks: ["0.0.0.0/0"]
        - protocol: tcp
          from_port: 22
          to_port: 22
          cidr_blocks: ["0.0.0.0/0"]
      - name: ${cluster_name}-worker
        description: Security group for worker nodes
        vpc_name: ${vpc_name}
        rules:
        - protocol: tcp
          from_port: 30000
          to_port: 32767
          cidr_blocks: ["0.0.0.0/0"]
        - protocol: tcp
          from_port: 22
          to_port: 22
          cidr_blocks: ["0.0.0.0/0"]
      - name: ${cluster_name}-internal
        description: Security group for internal cluster communication
        vpc_name: ${vpc_name}
        rules:
        - protocol: -1
          from_port: -1
          to_port: -1
          self: true 